### ISSUE TITLE
Problem with FitNesse v20161106?

### ISSUE THREAD

**Issue by NicoleRauch** [noamtcohen/SlimJS#14]
I am using SlimJS with FitNesse v20160515 just fine. But when I changed the FitNesse version to v20161106 (without changing anything else, just be replacing the fitnesse-standalone.jar), I could not run my SlimJS tests any more. The SlimJS test page shows:

```
Unable to start test system 'slim': fitnesse.slim.SlimError: Got invalid slim header from client. Read the following:
```

and the page execution log shows:

```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:1
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1337:19)
    at listenInCluster (net.js:1395:12)
    at Server.listen (net.js:1479:7)
    at startServer (.../node_modules/slimjs/src/tcp/SlimTcpServer.js:27:60)
    at SlimTcpServer.start (.../node_modules/slimjs/src/tcp/SlimTcpServer.js:24:9)
    at new SlimJS (.../node_modules/slimjs/src/SlimJS.js:20:19)
    at Object.<anonymous> (.../node_modules/slimjs/src/SlimJS.js:11:1)
    at Module._compile (module.js:612:30)
```

Any ideas on how this can be resolved?

**Comment by NicoleRauch** [comment]
I'm using SlimJS version 2.1.4.

**Comment by noamtcohen** [comment]
I don't know what they changed in FitNesse, maybe you can look at there repo and try to see what changed in the header. I'm sorry but I don't have time for this right now.

**Comment by NicoleRauch** [comment]
I figured this out (but forgot to comment here, sorry).

Slim can now communicate via stdin and stdout, and this new feature has become the default. A compatibility mode can be triggered by setting

```
!define SLIM_PORT {9086}
```
(or any other port except 1).

With this setting, SlimJS works together with the newest FitNesse release.
